### PR TITLE
remove typhon and vendor dir

### PR DESCRIPTION
**Pull request by DaytonG**
Ref: https://github.com/redboxllc/scuttle/pull/47

Removed the tilt changes, though I think I'll keep that other PR open for now and just use it for the tilt proposal.

In this PR:
- removed typhon (which drastically reduces security footprint)
- removed vendor/ dir in favor of go modules

### CODE REVIEW

**Comment by DaytonG** [comment]
Ping on this, if there's anyone available to review.

**Comment by linjmeyer** [comment]
Hey @DaytonG I didn't forget about you - just on vacation at the moment.  I'll take a look next week.

**Comment by DaytonG** [comment]
Thanks! Hopefully this can get a look soon.

**Comment by linjmeyer** [comment]
Hello, I am leaving the Redbox org and will close this PR as I won't have time to review and it is several months old already

**Pull request closed without merging**
