### PR TITLE
Bump golang to 1.21

### PR DESCRIPTION
**Pull request by neiljain**
based off of https://github.com/redboxllc/scuttle/pull/47 

- removed typhon (which drastically reduces security footprint)
- removed vendor/ dir in favor of go modules
- upgrade golang to 1.21.2

### CODE REVIEW

**Comment by kvij** [comment]
Hi @neiljain as you can see from https://github.com/redboxllc/scuttle/pull/60 the original author lost access.
A lot of what you did is already in my fork complete with ready to use binaries and docker container: https://github.com/kvij/scuttle
If there is anything missing please let me know and we can work on it :smiley: 

Removing the vendor dir however is not a good option for open source project. Vendoring is a feature of go modules and go modules are not a replacement.

**Comment by neiljain** [comment]
thanks. @kvij  close this PR and will use https://github.com/kvij/scuttle instead.

**Comment by linjmeyer** [comment]
Hey all, we have a new OSS option at The Aspen Group that we released today: https://github.com/tag-oss/rescuttle

Idea is the same, its a rewrite and is a bit more flexible than the original.  It will require a bit of a migration as the settings are different however, feel free to check it out and thanks @kvij for maintaining the fork!

**Comment by kvij** [comment]
Hey @linjmeyer as you can see from [v1.1.0](https://github.com/kvij/scuttle/releases/tag/v1.1.0) I took it a bit beyond just maintaining.
 I'm pleased to see that you are able to participate again although I hope that we soon do not need any form of scuttle anymore.

Also we seem to be competing now. While I am active to move people away from this version to my version I don't know what would be the best approach here. I do find it a bit sad that the rescuttle repo states that the Go scuttle is not maintained. If you want we can have a chat.

**Comment by linjmeyer** [comment]
Awesome, I'll check it out!  Ours has been in use for about a year internally, but unfortunately wasn't able to be open sourced at the time.  If community members decide to keep using your forked version that is all good with us, nothing wrong with having options.

Definitely agree too, ideally this is a problem that goes away and sidecars are treated as a special container by Kubernetes itself.. sure would make it simpler.

**Comment by kvij** [comment]
Thanks I was a bit worried you wanted full control back. Will list
rescuttle as an alternative and add you as a reviewer on that mr. Would
appreciate it if you could do the same with kvij/scuttle.

We have some great things on the way. First of all there is Istio ambient
that is basically sidecar free unless you really want it. And then there is
kubernetes 1.28 with native sidecar support (as a special init container
that keeps running until the main container finishes). Will take some time
for everyone to migrate of course.

**Pull request closed without merging**
