### PR TITLE
Update base image to golang 1.19.1

### PR DESCRIPTION
**Pull request by arcaartem**
Updates base image to the latest golang version

### CODE REVIEW

**Comment by PackiarajSakkananGW** [comment]
Can this PR be merged?
Have quite a bit of vulnerablity with current version 1.17.9

thanks

**Comment by PackiarajSakkananGW** [comment]
Can this PR be ammeded to use go lang 1.19.3

**Comment by linjmeyer** [comment]
Hi @PackiarajSakkananGW, I don't think this is being maintained any longer.  See my comment here: https://github.com/redboxllc/scuttle/pull/60#issuecomment-1342925256

**Comment by linjmeyer** [comment]
@arcaartem if you are still looking for a maintained alternative, we just open sourced one: https://github.com/tag-oss/rescuttle.  Feel free to check it out!

**Pull request closed without merging**
